/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xyzCorp.h"

/* 
 * xyzCorp_variables_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

oid xyzCorp_variables_oid[] = { 1,3,6,1,3,57 };

/* 
 * variable4 xyzCorp_variables:
 *   this variable defines function callbacks and type return information 
 *   for the xyzCorp mib section 
 */

struct variable4 xyzCorp_variables[] = {
/*  magic number        , variable type , ro/rw , callback fn  , L, oidsuffix */
#define FSSENTFILES		1
{FSSENTFILES,  ASN_COUNTER,  NETSNMP_OLDAPI_RONLY,
 var_xyzCorp, 2,  { 5,1 }},
#define FSRECEIVEDFILES		2
{FSRECEIVEDFILES,  ASN_COUNTER,  NETSNMP_OLDAPI_RONLY,
 var_xyzCorp, 2,  { 5,2 }},
#define FSREMOTESERVER		3
{FSREMOTESERVER,  ASN_IPADDRESS,  NETSNMP_OLDAPI_RWRITE,
 var_xyzCorp, 2,  { 5,3 }},
#define FSREMOTESERVERPORT		4
{FSREMOTESERVERPORT,  ASN_GAUGE,  NETSNMP_OLDAPI_RWRITE,
 var_xyzCorp, 2,  { 5,4 }},
#define FSLOCALSERVERPORT		5
{FSLOCALSERVERPORT,  ASN_GAUGE,  NETSNMP_OLDAPI_RWRITE,
 var_xyzCorp, 2,  { 5,5 }},

};
/*    (L = length of the oidsuffix) */


/** Initializes the xyzCorp module */
void
init_xyzCorp(void)
{

    DEBUGMSGTL(("xyzCorp", "Initializing\n"));

    /* register ourselves with the agent to handle our mib tree */
    REGISTER_MIB("xyzCorp", xyzCorp_variables, variable4,
               xyzCorp_variables_oid);

    /* place any other initialization junk you need here */
}

/*
 * var_xyzCorp():
 *   This function is called every time the agent gets a request for
 *   a scalar variable that might be found within your mib section
 *   registered above.  It is up to you to do the right thing and
 *   return the correct value.
 *     You should also correct the value of "var_len" if necessary.
 *
 *   Please see the documentation for more information about writing
 *   module extensions, and check out the examples in the examples
 *   and mibII directories.
 */
unsigned char *
var_xyzCorp(struct variable *vp, 
                oid     *name, 
                size_t  *length, 
                int     exact, 
                size_t  *var_len, 
                WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    if (header_generic(vp,name,length,exact,var_len,write_method)
                                  == MATCH_FAILED )
    return NULL;

    /* 
   * this is where we do the value assignments for the mib results.
   */
   
    switch(vp->magic) {
    case FSSENTFILES:
        long_ret = 123;	/* XXX */
        return (u_char*) &long_ret;
    // case FSRECEIVEDFILES:
    //     VAR = 456;	/* XXX */
    //     return (u_char*) &VAR;
    // case FSREMOTESERVER:
    //     *write_method = write_fsRemoteServer;
    //     VAR = 192;	/* XXX */
    //     return (u_char*) &VAR;
    // case FSREMOTESERVERPORT:
    //     *write_method = write_fsRemoteServerPort;
    //     VAR = 789;	/* XXX */
    //     return (u_char*) &VAR;
    // case FSLOCALSERVERPORT:
    //     *write_method = write_fsLocalServerPort;
    //     VAR = 0;	/* XXX */
    //     return (u_char*) &VAR;
    default:
      ERROR_MSG("");
    }
    return NULL;
}





int
write_fsRemoteServer(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    in_addr_t value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_IPADDRESS) {
              fprintf(stderr, "write to xyzCorp not ASN_IPADDRESS\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(in_addr_t)) {
              fprintf(stderr,"write to xyzCorp: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (in_addr_t *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}


int
write_fsRemoteServerPort(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    u_long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_GAUGE) {
              fprintf(stderr, "write to xyzCorp not ASN_GAUGE\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(u_long)) {
              fprintf(stderr,"write to xyzCorp: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (u_long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}


int
write_fsLocalServerPort(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    u_long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_GAUGE) {
              fprintf(stderr, "write to xyzCorp not ASN_GAUGE\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(u_long)) {
              fprintf(stderr,"write to xyzCorp: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (u_long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}

