/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef XYZCORP_H
#define XYZCORP_H

/* function declarations */
void init_xyzCorp(void);
FindVarMethod var_xyzCorp;
    WriteMethod write_fsRemoteServer;
    WriteMethod write_fsRemoteServerPort;
    WriteMethod write_fsLocalServerPort;

#endif /* XYZCORP_H */
